- id: mermaid-checker
  name: Mermaid Template Checker
  description: Validates mermaid flowcharts in markdown files according to template rules
  entry: deno run --allow-read main.ts
  language: system
  types: [markdown]
  pass_filenames: false
  args: ["."] 